[alembic]
# Путь к папке миграций
script_location = alembic

# Строка подключения к БД оставляем пустой —
# она читается из .env через env.py
sqlalchemy.url = 

[loggers]
keys = root,sqlalchemy,alembic,file

[handlers]
keys = console,file

[formatters]
keys = generic,extended

[logger_root]
level = WARN
handlers = console,file
qualname =

[logger_sqlalchemy]
level = WARN
handlers = file
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console,file
qualname = alembic

[logger_file]
level = INFO
handlers = file
qualname = file

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_file]
class = FileHandler
args = ("alembic_migrations.log", "a")
level = INFO
formatter = extended

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s

[formatter_extended]
format = %(asctime)s %(levelname)-5.5s [%(name)s] (%(filename)s:%(lineno)d) %(message)s
datefmt = %Y-%m-%d %H:%M:%S
