"""add strength_multiplier to strategies

Revision ID: 1b13a68ea4ac
Revises: de6836c3623b
Create Date: 2026-05-07 11:12:35.059208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b13a68ea4ac'
down_revision: Union[str, Sequence[str], None] = 'de6836c3623b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('strength_multiplier', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'strength_multiplier')
    # ### end Alembic commands ###
