"""add backtest_trades ↔ signal relationship

Revision ID: 682bbfaca8b5
Revises: ec00dbe84c59
Create Date: 2026-05-14 17:34:20.478064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682bbfaca8b5'
down_revision: Union[str, Sequence[str], None] = 'ec00dbe84c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_trade_id'), table_name='signals')
    op.drop_constraint(op.f('signals_trade_id_fkey'), 'signals', type_='foreignkey')
    op.drop_column('signals', 'trade_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('trade_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('signals_trade_id_fkey'), 'signals', 'trades', ['trade_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_signals_trade_id'), 'signals', ['trade_id'], unique=False)
    # ### end Alembic commands ###
