"""fix userstatus enum

Revision ID: b4052dd3b025
Revises: 3c7334e3bc33
Create Date: 2026-05-06 11:35:20.491137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4052dd3b025'
down_revision: Union[str, Sequence[str], None] = '3c7334e3bc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # создаём ENUM тип вручную
    userstatus = sa.Enum('active', 'blocked', name='userstatus')
    userstatus.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=False),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_logs_id'), 'risk_logs', ['id'], unique=False)

    op.create_table('strategies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('enabled_indicators', sa.JSON(), nullable=False),
        sa.Column('entry_conditions', sa.JSON(), nullable=True),
        sa.Column('ema_short', sa.Integer(), nullable=True),
        sa.Column('ema_long', sa.Integer(), nullable=True),
        sa.Column('rsi_period', sa.Integer(), nullable=True),
        sa.Column('atr_period', sa.Integer(), nullable=True),
        sa.Column('macd_fast', sa.Integer(), nullable=True),
        sa.Column('macd_slow', sa.Integer(), nullable=True),
        sa.Column('macd_signal', sa.Integer(), nullable=True),
        sa.Column('stochastic_period', sa.Integer(), nullable=True),
        sa.Column('bollinger_period', sa.Integer(), nullable=True),
        sa.Column('stop_loss', sa.Float(), nullable=False),
        sa.Column('take_profit_targets', sa.JSON(), nullable=False),
        sa.Column('take_profit_distribution', sa.JSON(), nullable=True),
        sa.Column('trailing_stop', sa.Boolean(), nullable=True),
        sa.Column('trailing_mode', sa.String(), nullable=True),
        sa.Column('allocation_percent', sa.Float(), nullable=False),
        sa.Column('leverage', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)

    op.create_table('backtest_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(length=20), nullable=False),
        sa.Column('strategy', sa.String(length=50), nullable=False),
        sa.Column('winrate', sa.Float(), nullable=False),
        sa.Column('avg_profit', sa.Float(), nullable=False),
        sa.Column('max_drawdown', sa.Float(), nullable=False),
        sa.Column('sharpe', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_reports_id'), 'backtest_reports', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_reports_strategy'), 'backtest_reports', ['strategy'], unique=False)
    op.create_index(op.f('ix_backtest_reports_symbol'), 'backtest_reports', ['symbol'], unique=False)
    op.create_index(op.f('ix_backtest_reports_user_id'), 'backtest_reports', ['user_id'], unique=False)

    op.add_column('signals', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('source', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_signals_user_id'), 'signals', ['user_id'], unique=False)
    op.drop_constraint(op.f('signals_user_id_fkey'), 'signals', type_='foreignkey')
    op.create_foreign_key(None, 'signals', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.add_column('trades', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('profit_loss', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('leverage', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('signal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trades_signal_id'), 'trades', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.drop_constraint(op.f('trades_user_id_fkey'), 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'signals', ['signal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.add_column('users', sa.Column('status', userstatus, nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'status')

    # удаляем ENUM тип
    userstatus = sa.Enum('active', 'blocked', name='userstatus')
    userstatus.drop(op.get_bind())

    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key(op.f('trades_user_id_fkey'), 'trades', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_signal_id'), table_name='trades')
    op.drop_column('trades', 'signal_id')
    op.drop_column('trades', 'leverage')
    op.drop_column('trades', 'profit_loss')
    op.drop_column('trades', 'exit_price')
    op.drop_column('trades', 'entry_price')

    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.create_foreign_key(op.f('signals_user_id_fkey'), 'signals', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_signals_user_id'), table_name='signals')
    op.drop_column('signals', 'source')
    op.drop_column('signals', 'confidence')

    op.drop_index(op.f('ix_backtest_reports_user_id'), table_name='backtest_reports')
    op.drop_index(op.f('ix_backtest_reports_symbol'), table_name='backtest_reports')
    op.drop_index(op.f('ix_backtest_reports_strategy'), table_name='backtest_reports')
    op.drop_index(op.f('ix_backtest_reports_id'), table_name='backtest_reports')
    op.drop_table('backtest_reports')

    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')

    op.drop_index(op.f('ix_risk_logs_id'), table_name='risk_logs')
    op.drop_table('risk_logs')
    # ### end Alembic commands ###
