"""Added tabl indicators

Revision ID: caea442463f8
Revises: 68ed19db22bd
Create Date: 2026-05-08 18:25:52.478486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caea442463f8'
down_revision: Union[str, Sequence[str], None] = '68ed19db22bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_name'), 'indicators', ['name'], unique=False)
    op.create_index(op.f('ix_indicators_pair'), 'indicators', ['pair'], unique=False)
    op.create_index(op.f('ix_indicators_timestamp'), 'indicators', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicators_timestamp'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_pair'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_name'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
