"""add exchange_order_id to trades and new tables

Revision ID: de6836c3623b
Revises: f345f9d5e3a3
Create Date: 2026-05-06 18:16:55.554548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6836c3623b'
down_revision: Union[str, Sequence[str], None] = 'f345f9d5e3a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('exchange_order_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_trades_exchange_order_id'), 'trades', ['exchange_order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_exchange_order_id'), table_name='trades')
    op.drop_column('trades', 'exchange_order_id')
    # ### end Alembic commands ###
