"""add new fields and tables

Revision ID: ec00dbe84c59
Revises: 30ff8daa0faf
Create Date: 2026-05-14 16:13:27.874184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec00dbe84c59'
down_revision: Union[str, Sequence[str], None] = '30ff8daa0faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('trade_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_signals_trade_id'), 'signals', ['trade_id'], unique=False)
    op.create_foreign_key(None, 'signals', 'trades', ['trade_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_index(op.f('ix_signals_trade_id'), table_name='signals')
    op.drop_column('signals', 'trade_id')
    # ### end Alembic commands ###
