"""add indicators fields to strategies

Revision ID: ecfb07128c9a
Revises: 682bbfaca8b5
Create Date: 2026-05-18 18:33:18.322584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecfb07128c9a'
down_revision: Union[str, Sequence[str], None] = '682bbfaca8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('obv_enabled', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('volume_period', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('vwap_enabled', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('ichimoku_tenkan', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('ichimoku_kijun', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('ichimoku_senkou', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'enabled')
    op.drop_column('strategies', 'ichimoku_senkou')
    op.drop_column('strategies', 'ichimoku_kijun')
    op.drop_column('strategies', 'ichimoku_tenkan')
    op.drop_column('strategies', 'vwap_enabled')
    op.drop_column('strategies', 'volume_period')
    op.drop_column('strategies', 'obv_enabled')
    # ### end Alembic commands ###
