"""add risk_settings table

Revision ID: f345f9d5e3a3
Revises: b4052dd3b025
Create Date: 2026-05-06 15:55:21.314194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f345f9d5e3a3'
down_revision: Union[str, Sequence[str], None] = 'b4052dd3b025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_risk_per_trade', sa.Float(), nullable=False),
    sa.Column('max_open_trades', sa.Integer(), nullable=False),
    sa.Column('max_daily_loss', sa.Float(), nullable=False),
    sa.Column('max_leverage', sa.Integer(), nullable=False),
    sa.Column('cooldown_between_trades', sa.Integer(), nullable=False),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=False),
    sa.Column('dynamic_allocation', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_settings_id'), 'risk_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_settings_id'), table_name='risk_settings')
    op.drop_table('risk_settings')
    # ### end Alembic commands ###
